name: acamp_kids
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.9.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  get: ^4.1.4
  carousel_pro: ^1.0.0
  carousel_slider: ^4.0.0

  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  firebase_database: ^6.1.2
#  flutter_facebook_login: ^3.0.0
#  flutter_facebook_auth: ^3.3.3
  # google_sign_in: ^5.0.2
  provider: ^5.0.0
  flutter_signin_button: ^2.0.0
  cloud_firestore: ^1.0.0
  meta: ^1.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  html: ^0.15.0
  path_provider: ^2.0.4
  shared_preferences: ^2.0.7
  ntp: ^1.0.7
  cron: ^0.3.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    #LOGIN
    - assets/img_login/facebook.jpg
    - assets/img_login/google.jpg
    - assets/img_login/logo.png
    - assets/images/perfil.jpeg

    #Principal
    - assets/principal/Act1.png
    - assets/principal/Act2.png
    - assets/principal/Act3.png
    - assets/principal/Act4.png
    - assets/principal/Act5.png
    - assets/principal/Act6.png
    - assets/principal/Action1.png
    - assets/principal/Action2.png
    - assets/principal/Boot.png
    - assets/principal/BotaoMais.png
    - assets/principal/BotaoMenos.png
    - assets/principal/BotaoOK.png
    - assets/principal/Day.png
    - assets/principal/Face1.png
    - assets/principal/Face3.png
    - assets/principal/Face2.png
    - assets/principal/Fundo1.png
    - assets/principal/Fundo2.png
    - assets/principal/Fundo3.png
    - assets/principal/Nav1.png
    - assets/principal/Nav2.png
    - assets/principal/Nav3.png
    - assets/principal/fundotela.png
    - assets/principal/menu1.png
    - assets/principal/menu2.png
    - assets/principal/menu3.png
    - assets/principal/NotFace.png
    - assets/principal/Perfil.png
    - assets/principal/Trofeu3.png
    - assets/principal/Trofeu4.png
    - assets/principal/TrofeuMaior.png
    - assets/principal/Trophy_Bronze.png
    - assets/principal/Trophy_Gold.png
    - assets/principal/Trophy_Silver.png
    - assets/principal/Trophy_NoTrophy.png

  #Semanal
    - assets/semanal/Act0.png
    - assets/semanal/Act1.png
    - assets/semanal/Act2.png
    - assets/semanal/Act3.png
    - assets/semanal/Act4.png
    - assets/semanal/Act5.png
    - assets/semanal/Action1.png
    - assets/semanal/Boot.png
    - assets/semanal/Day.png
    - assets/semanal/Face1.png
    - assets/semanal/Face2.png
    - assets/semanal/Face3.png
    - assets/semanal/Nav1.png
    - assets/semanal/Nav2.png
    - assets/semanal/Nav3.png
    - assets/semanal/BarTrofeu1.png
    - assets/semanal/BarTrofeuAct.png
    - assets/semanal/Back.png
    - assets/semanal/Mod1.png
    - assets/semanal/ModF.png

  #menu
    - assets/menu/Ajuda.png
    - assets/menu/Opcoes.png
    - assets/menu/Sair.png
    - assets/menu/ActionMenu.png

  #login
    - assets/login/Trofeu1.png
    - assets/login/Trofeu2.png
    - assets/login/Facebook.png
    - assets/login/Google.png
    - assets/login/Login.png

  #popUp
    - assets/popUp/Alert.png
    - assets/popUp/Fundo4.png
    - assets/popUp/PopUp3.png
    - assets/popUp/PopUp5.png
    - assets/popUp/PopUp6.png

  fonts:
    - family: Riffic
      fonts:
        - asset: fonts/RifficFree-Bold.otf
    - family: Bahnschrift
      fonts:
        - asset: fonts/Bahnschrift.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: RifficFree-Bold
  #     fonts:
  #       - asset: fonts/RifficFree-Bold.tff
  #   - family: Bahnschrift
  #     fonts:
  #       - asset: fonts/Bahnschrift.ttf
        # - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
